// <auto-generated />
using System;
using DatabaseAccessLayer.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseAccessLayer.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    [Migration("20260424205916_AddNewRulesForPage")]
    partial class AddNewRulesForPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chapters", null, t =>
                        {
                            t.HasCheckConstraint("CK_Chapter_Order_Min", "[Order] > 0");
                        });
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Page_Image_NotEmpty", "Image IS NOT NULL AND DATALENGTH(Image) > 0");

                            t.HasCheckConstraint("CK_Page_Order_Min", "[Order] > 0");
                        });
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.ReadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReadItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReadItem_Title_NotEmpty", "LEN(TRIM(Title)) > 0");

                            t.HasCheckConstraint("CK_ReadItem_Type_NotEmpty", "LEN(TRIM(Type)) > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
