// <auto-generated />
using System;
using DatabaseAccessLayer.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseAccessLayer.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    [Migration("20260629202224_AddPageChapterConnection")]
    partial class AddPageChapterConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdReadItem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdReadItem");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChapter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChapter");

                    b.ToTable("Pages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Page_Image_NotEmpty", "Image IS NOT NULL AND DATALENGTH(Image) > 0");

                            t.HasCheckConstraint("CK_Page_Order_Min", "[Order] > 0");
                        });
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.ReadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CoverImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValue(new byte[] { 0 });

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Rating");

                    b.HasIndex("Title");

                    b.ToTable("ReadItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReadItem_CoverImage_NotEmpty", "CoverImage IS NOT NULL AND DATALENGTH(CoverImage) > 0");

                            t.HasCheckConstraint("CK_ReadItem_Title_NotEmpty", "LEN(TRIM(Title)) > 0");

                            t.HasCheckConstraint("CK_ReadItem_Type_NotEmpty", "LEN(TRIM(Type)) > 0");
                        });
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.ReadItemTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdReadItem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTag")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id", "IdReadItem", "IdTag");

                    b.HasIndex("IdReadItem");

                    b.HasIndex("IdTag");

                    b.ToTable("ReadItemTags", (string)null);
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tags", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tag_Name_NotEmpty", "LEN(TRIM(Name)) > 0");
                        });
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Chapter", b =>
                {
                    b.HasOne("DatabaseAccessLayer.Entities.ReadItem", "ReadItem")
                        .WithMany("Chapters")
                        .HasForeignKey("IdReadItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadItem");
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Page", b =>
                {
                    b.HasOne("DatabaseAccessLayer.Entities.Chapter", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("IdChapter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.ReadItemTag", b =>
                {
                    b.HasOne("DatabaseAccessLayer.Entities.ReadItem", "ReadItem")
                        .WithMany("ReadItemTags")
                        .HasForeignKey("IdReadItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAccessLayer.Entities.Tag", "Tag")
                        .WithMany("ReadItemTags")
                        .HasForeignKey("IdTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Chapter", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.ReadItem", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("ReadItemTags");
                });

            modelBuilder.Entity("DatabaseAccessLayer.Entities.Tag", b =>
                {
                    b.Navigation("ReadItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
